### ISSUE TITLE
messed Pad desoldering mirco USB port

### ISSUE THREAD

**Issue by timehlers** [Quantum-cross/sam-fusee-launcher-internal#3]
Hi,

sorry for opening an issue. It's just that I seem to have messed up the PINs from the USB port on the trinked M0 while desoldering the micro USB port. Do you know if there are alternative PINs for D+ and D-? I read "USB" on one of the connector-row-PINs, is this eventually one of these PINs?

Thanks

Tim

**Comment by GhostlyCrowd** [comment]
If you look at the PCB you will see that D+ and D- go right to the ATSAMD21E18 and you will have to solder to it directly.

**Comment by timehlers** [comment]
Yes, I see. That's even more tricky to solder. But thanks for the reply.
