### ISSUE TITLE
When converting bin / h...

### ISSUE THREAD

**Issue by Auvrae** [Quantum-cross/sam-fusee-launcher-internal#4]
Hello whilst converting with your  python script I keep getting this error...

"reading file: C:\bin.bin
[                    ] 0%Traceback (most recent call last):
  File "binConverter.py", line 42, in <module>
    stringBuffer += "0x"+binascii.hexlify(byte).decode('ascii')+", "
TypeError: a bytes-like object is required, not 'int'"

I'm using python 3.7.

Thanks.

**Comment by Quantum-cross** [comment]
Sorry, try python 2, I think there's a python3 capable version in one of the other forked repositories. I haven't had much time to update this repository

**Comment by Auvrae** [comment]
I’ll definitely try 2. I’ll also look into a compatible 3 version in the forks. I’ll let you know later tonight if my findings, thanks a bunch.

**Comment by Auvrae** [comment]
update,

using python 2.7 it works perfectly.
thank you for the tip!
may i suggest adding that to the guide?
